name: experimentalcrosscompiling

on:
  workflow_dispatch:

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu_latest
    name: Build on ubuntu_latest  aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest
          run: |
            cargo install perseus-cli
            perseus deploy
            mkdir output_folder
            mv pkg/ output_folder/
          
      - uses: actions/upload-artifact@v3
        with:
          name: compiledperseussite
          path: output_folder/
